version: '1.0'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ecommerce_app
    ports:
      - "5432:5432"

  app:
    image: app-login-back-app
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:1234@db/ecommerce_app
    depends_on:
      - db